ktor:
  development: true
  application:
    modules:
      - ro.bankar.ApplicationKt.module
  deployment:
    port: 8080
    sslPort: 8443
    watch:
      - classes
      - resources
  security:
    ssl:
      keyStore: keystore.jks
      keyAlias: bankar
      keyStorePassword: $KEYSTORE_PASS
      privateKeyPassword: $KEYSTORE_PASS